# Generated by Django 5.2.9 on 2026-02-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_turfownerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfownerprofile',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Full name of the owner', max_length=100),
        ),
    ]
