# Generated by Django 5.2.9 on 2026-01-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenience_fee_enabled', models.BooleanField(default=True, null=True)),
                ('convenience_fee_type', models.CharField(choices=[('FLAT', 'Flat Fee'), ('PERCENT', 'Percentage')], default='FLAT', max_length=10, null=True)),
                ('convenience_fee_value', models.DecimalField(decimal_places=2, default=20.0, help_text='Flat amount (₹) or Percentage (%) based on type', max_digits=10, null=True)),
                ('default_commission_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
