# Generated by Django 5.2.9 on 2026-02-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='ads_enabled',
            field=models.BooleanField(default=False, help_text='Master toggle for the Ad Campaign system across the platform.'),
        ),
    ]
