# Generated by Django 5.2.9 on 2026-02-01 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_platformsettings_ads_enabled'),
        ('turfs', '0008_turf_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('OWNER_APPROVED', 'Owner Application Approved'), ('OWNER_REJECTED', 'Owner Application Rejected'), ('TURF_APPROVED', 'Turf Approved'), ('TURF_REJECTED', 'Turf Rejected'), ('TURF_HIDDEN', 'Turf Hidden'), ('TURF_SHOWN', 'Turf Made Visible')], max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for rejection or action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_turf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turfs.turf')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Action Log',
                'verbose_name_plural': 'Admin Action Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
