# Generated by Django 5.2.9 on 2026-01-31 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_name', models.CharField(max_length=255)),
                ('ad_type', models.CharField(choices=[('BANNER', 'Banner Ad'), ('SPONSORED_LISTING', 'Sponsored Turf Listing'), ('PROMOTION_CARD', 'Featured Promotion Card'), ('EVENT', 'Event / Tournament Promotion')], max_length=50)),
                ('placement', models.CharField(choices=[('HOME', 'Home Page'), ('LISTING', 'Turf Listing Page'), ('SEARCH', 'Search Results'), ('CONFIRMATION', 'Booking Confirmation')], default='HOME', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('redirect_url', models.URLField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('EXPIRED', 'Expired'), ('PENDING_APPROVAL', 'Pending Approval')], default='PENDING_APPROVAL', max_length=20)),
                ('target_city', models.CharField(blank=True, max_length=100, null=True)),
                ('pricing_model', models.CharField(choices=[('CPM', 'Cost Per Thousand Views (CPM)'), ('CPC', 'Cost Per Click (CPC)'), ('FIXED', 'Fixed Price')], default='FIXED', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Rate based on pricing model', max_digits=10)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('impressions_count', models.PositiveIntegerField(default=0)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='ads.adcampaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='ads.adcampaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
