# Generated by Django 5.2.9 on 2026-01-31 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='advertiser_name',
            field=models.CharField(help_text='Brand or Business Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='current_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Current Spend'),
        ),
    ]
