# Generated by Django 5.2.9 on 2026-01-31 21:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_adcampaign_advertiser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adcampaign',
            old_name='clicks_count',
            new_name='clicks',
        ),
        migrations.RenameField(
            model_name='adcampaign',
            old_name='impressions_count',
            new_name='impressions',
        ),
        migrations.RemoveField(
            model_name='adcampaign',
            name='current_revenue',
        ),
        migrations.RemoveField(
            model_name='adcampaign',
            name='pricing_model',
        ),
        migrations.RemoveField(
            model_name='adcampaign',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='adcampaign',
            name='target_city',
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='cost_model',
            field=models.CharField(choices=[('CPM', 'Cost Per Thousand Impressions (CPM)'), ('CPC', 'Cost Per Click (CPC)'), ('FIXED', 'Fixed Price (per Day)')], default='CPC', max_length=10),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per Click, 1000 Impressions, or Day', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='daily_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='ad_type',
            field=models.CharField(choices=[('BANNER', 'Banner Ad'), ('SPONSORED_TURF', 'Sponsored Turf Listing'), ('PROMOTION_CARD', 'Featured Promotion Card')], max_length=50),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='advertiser_name',
            field=models.CharField(help_text='Business Name for the ad', max_length=255),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/creatives/'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='placement',
            field=models.CharField(choices=[('HOME', 'Home Page'), ('SEARCH', 'Search Results'), ('LISTING', 'Turf Listing Detail')], max_length=50),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('PENDING_APPROVAL', 'Pending Approval')], default='PENDING_APPROVAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='adclick',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='ads.adcampaign'),
        ),
        migrations.AlterField(
            model_name='adimpression',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression_logs', to='ads.adcampaign'),
        ),
    ]
