# Generated by Django 5.2.9 on 2026-01-30 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turfs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turf',
            name='sports',
            field=models.ManyToManyField(related_name='turfs', to='turfs.sporttype'),
        ),
        migrations.AddField(
            model_name='turfimage',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='turfs.turf'),
        ),
    ]
