# Generated by Django 5.2.10 on 2026-01-31 07:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='map_share_url',
            field=models.URLField(blank=True, help_text='Google Maps Share Link', null=True),
        ),
        migrations.AddField(
            model_name='turfimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 31, 7, 41, 56, 216855, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TurfVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Small promo video (max 15s)', upload_to='turf_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='turfs.turf')),
            ],
        ),
    ]
