# Generated by Django 5.2.9 on 2026-01-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0003_turf_map_share_url_turfimage_created_at_turfvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='turf_images/'),
        ),
        migrations.AlterField(
            model_name='turfvideo',
            name='video',
            field=models.FileField(help_text='Small promo video (max 15s)', max_length=500, upload_to='turf_videos/'),
        ),
    ]
