# Generated by Django 5.2.9 on 2026-01-31 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0004_alter_turfimage_image_alter_turfvideo_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BOOKING', 'New Booking'), ('CANCELLATION', 'Booking Cancelled'), ('STATUS_CHANGE', 'Status Changed'), ('PRICE_CHANGE', 'Price Updated'), ('INFO', 'Information')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='turfs.turf')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
