# Generated by Django 5.2.9 on 2026-01-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0005_turfactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
