# Generated by Django 5.2.9 on 2026-02-01 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0006_alter_turf_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='closed_reason',
            field=models.CharField(blank=True, help_text="Public reason for today's closure", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='turf',
            name='is_open_today',
            field=models.BooleanField(default=True, help_text="Manual toggle for today's status"),
        ),
        migrations.CreateModel(
            name='EmergencyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True)),
                ('turf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_block', to='turfs.turf')),
            ],
        ),
        migrations.CreateModel(
            name='TurfClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='turfs.turf')),
            ],
        ),
        migrations.CreateModel(
            name='TurfDayAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_open', models.BooleanField(default=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_availability', to='turfs.turf')),
            ],
            options={
                'unique_together': {('turf', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='TurfSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_slots', to='turfs.turf')),
            ],
            options={
                'unique_together': {('turf', 'start_time', 'end_time')},
            },
        ),
    ]
