# Generated by Django 5.2.9 on 2026-02-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0007_turf_closed_reason_turf_is_open_today_emergencyblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='rules',
            field=models.TextField(blank=True, help_text='Venue rules (e.g. No metal studs, reach 15 min early)'),
        ),
    ]
