# Generated by Django 5.2.9 on 2026-01-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_commission_percentage_booking_owner_earnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Original turf price', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='convenience_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Platform convenience fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='10% cut from base_amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total payable (Base + Fee)', max_digits=10),
        ),
    ]
