# Generated by Django 5.2.9 on 2026-02-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_base_amount_booking_convenience_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Time until which this reservation is held', null=True),
        ),
    ]
